/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ListMethodsTest {
    @Test void shouldCallTheConsumerWithEachElements() {
        String[] greetings = "Hi Hello Welcome".split(" ");
        ListMethods.forEach(greetings, str -> {
            assertTrue(str.matches("Hi|Hello|Welcome"), "shouldCallTheConsumerWithEachElements");
        });
    }

    @Test
    void shouldNotCallConsumerIfListIsEmpty () {
        ListMethods.forEach(new String[]{}, str -> fail());
    }
}
