/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.list;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ListMethodsTest {
  @Test
  void forEachShouldCallTheConsumerWithEachElements() {
    String[] greetings = "Hi Hello Welcome".split(" ");
    ListMethods.forEach(greetings, str -> {
      assertTrue(str.matches("Hi|Hello|Welcome"), "shouldCallTheConsumerWithEachElements");
    });
  }

  @Test
  void forEachShouldNotCallConsumerIfListIsEmpty() {
    ListMethods.forEach(new String[]{}, str -> fail());
  }

  @Test
  void reduceShouldGoThroughAllElementsAndProduceResult() {
    Character[] characters = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'};

    Reducer<Character, Integer> vowelCounter = (currCount, currChar) -> {
      if (("" + currChar).matches("[aeiou]")) {
        return currCount + 1;
      }
      return currCount;
    };

    final Integer vowelCount = ListMethods.reduce(characters, vowelCounter, 0);
    assertEquals(vowelCount, 3, "reduceShouldGoThroughAllElementsAndProduceResult");
  }

  @Test
  void reduceShouldReturnInitialContextForEmptyList() {
    final Integer vowelCount = ListMethods.reduce(new Character[]{}, (currCount, currChar) -> {
      fail();
      return null;
    }, 0);
    assertEquals(vowelCount, 0, "reduceShouldGoThroughAllElementsAndProduceResult");
  }

  @Test
  void filterShouldProvideListOfValidatedValuesOnly() {
    Integer[] numbers = {0, 1, 2, 3, 4, 5};
    Integer[] evens = ListMethods.filter(numbers, num -> num % 2 == 0);
    assertArrayEquals(new Integer[]{0, 2, 4}, evens, "filterShouldProvideListOfValidatedValuesOnly");
  }

  @Test
  void filterShouldProvideEmptyListWhenNoElementsIsValidated() {
    Integer[] numbers = {1, 3, 5, 7};
    Integer[] evens = ListMethods.filter(numbers, num -> num % 2 == 0);
    assertArrayEquals(new Integer[]{}, evens, "filterShouldProvideEmptyListWhenNoElementsIsValidated");
  }

  @Test
  void filterShouldProvideEmptyListIfEmptyListGiven() {
    Integer[] evens = ListMethods.filter(new Integer[]{}, num -> fail());
    assertArrayEquals(new Integer[]{}, evens, "filterShouldProvideEmptyListIfEmptyListGiven");
  }

  @Test
  void mapShouldMapEachElement() {
    String[] greetings = "Hi Hello Welcome".split(" ");
    String[] mappedGreetings = ListMethods.map(greetings, str -> "." + str + ".", new String[]{"yo"});
    assertArrayEquals(new String[]{".Hi.", ".Hello.", ".Welcome."}, mappedGreetings);
  }

  @Test
  void mapShouldReturnEmptyListForEmptyGivenList() {
    String[] mappedGreetings = ListMethods.map(new String[]{}, str -> "." + str + ".", new String[]{});
    assertArrayEquals(new String[]{}, mappedGreetings);
  }
}
